apiVersion: v1
kind: Service
metadata:
  name: my-country-service2
spec:
  type: NodePort
  selector:
    app: my-country-service
  ports:
  - port: 8080        # port interne du conteneur
    targetPort: 8080  # correspond au containerPort défini dans le deployment
    nodePort: 32071   # port externe accessible depuis le navigateur
